apiVersion: v1  # Menentukan versi API Kubernetes yang digunakan untuk objek ini (v1 adalah versi API pertama).
kind: Secret  # Menunjukkan bahwa objek ini adalah Secret, yang digunakan untuk menyimpan data sensitif seperti kata sandi.
metadata:
  name: mongo-secret  # Nama unik untuk Secret ini.
type: Opaque  # Menunjukkan tipe data yang disimpan dalam Secret (dalam hal ini, data tidak dienkripsi).
data:
  MONGO_ROOT_USERNAME: YWRtaW4=  # Nama pengguna root MongoDB yang telah dienkripsi dalam format base64.
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==  # Kata sandi root MongoDB yang telah dienkripsi dalam format base64.
